title: Darshani Madumali
tagline: Darshani Madumali | Assistant Manager - Membership, Public Relations & Media | Green Enthusiast
description: Darshani Madumali, a passionate researcher with the curiosity of learning new trends and cutting-edge technologies.
url: https://darshanimadumali.me
author: Darshani Madumali
social:
    name: Darshani Madumali
    links:
        - https://linkedin.com/in/darshanimadumali
        - http://github.com/kaadmadumali
        - https://medium.com/@kaadmadumali
        - https://twitter.com/kaadmadumali
        - https://www.facebook.com/kaadmadumali
google-site-verification: fEdui_ngV2G7g_mi_AT06CdLuv_5yL4hu-kF-LITVTk
